name: Code Coverage

on:
  push:
    branches: ["main"]

jobs:
  upload_code_coverage:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Swift
        run: swift --version

      - name: Run tests
        run: |
          set -e

          for package_dir in LeetCodeSolutions/*; do
            if [[ ! -f "$package_dir/Package.swift" || ! -d "$package_dir/Sources" || ! -d "$package_dir/Tests" ]]; then
              continue
            fi

            package_name="$(basename "$package_dir")"
            swift test \
              --enable-code-coverage \
              --package-path "$package_dir" \
              --scratch-path "LeetCodeSolutions/.build/$package_name"
          done

      - name: Swift Coverage Conversion
        uses: sersoft-gmbh/swift-coverage-action@v4.0
        with:
            search-paths: "LeetCodeSolutions/.build"
            output: "LeetCodeSolutions/.build/debug"

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "LeetCodeSolutions/.build/debug/codecov.json"
          flags: swift
          slug: Alexey-Matjuk/LeetCodeSolutions
